[phases.setup]
nixPkgs = ["python312", "ffmpeg"]

[phases.install]
cmds = [
    "python3.12 -m pip install --upgrade pip",
    "python3.12 -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
